### ISSUE TITLE
Deploy runs on every master commit, not release tag

### ISSUE THREAD

**Issue by negebauer** [negebauer/IIC2173-Arqui#75]
Replace

```yml
filters:
              tags:
                only: /v\d+.\d+.\d+\Z/
              branches:
                only:
                  - master
```

with

```yml
filters:
              tags:
                only: /v\d+.\d+.\d+\Z/
#              branches:
#                only:
#                  - master
```
